language: python
fast_finish: true

python:
  - 2.7
  - 3.6

os:
  - linux

git:
  depth: 3

install:
  - pip -q install -e .[tests]
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pip install flake8;
    fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    flake8 .;
    fi
  - pytest -v

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    coverage run test/test_ongc.py;
    coverage report;
    coveralls;
    fi
