language: python
cache: pip
python:
  - "2.7"
  - "3.6"

matrix:
  fast_finish: true
  allow_failures:
    python: "2.7"

install:
  - pip -q install -e .[tests]
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pip install flake8;
    pip install pytest-cov;
    fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    flake8 .;
    pytest -v --cov=pyongc test/;
    else
    pytest -v;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    coveralls;
    fi

